/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "button-clear": { "creationFunction": "CreateGlassButton", "disabled": true, "onclick": "clearRecordsHandler", "text": "Clear" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "gauge1": { "continuous": true, "creationFunction": "CreateGauge", "criticalValue": 90, "imagePointer": "Images/gauge_needle.png", "minValue": 99, "pivotOffsetX": 28, "pivotOffsetY": 28, "pointerReach": 85, "startAngle": 45, "stopAngle": 315, "warningValue": 50 },
    "glassbutton": { "creationFunction": "CreateGlassButton", "onclick": "updateGauge", "text": "Update" },
    "info": { "backgroundStyle": "white", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "text": { "creationFunction": "CreateText", "text": "Google Username" },
    "text-amount-remaining": { "creationFunction": "CreateText" },
    "text-amount-spent": { "creationFunction": "CreateText" },
    "text-date": { "creationFunction": "CreateText", "text": "Next cycle:" },
    "text-until": { "creationFunction": "CreateText" },
    "text1": { "creationFunction": "CreateText", "text": "Password" },
    "text2": { "creationFunction": "CreateText", "text": "Monthly Budget" },
    "text3": { "creationFunction": "CreateText", "text": "E" },
    "text4": { "creationFunction": "CreateText", "text": "F" },
    "text5": { "creationFunction": "CreateText", "text": "Amount spent:" },
    "text6": { "creationFunction": "CreateText", "text": "Amount remaining:" },
    "text7": { "creationFunction": "CreateText", "text": "$" },
    "text9": { "creationFunction": "CreateText", "text": "Cycle End Date " }
};
